# -*- coding: utf-8 -*-

U1_GET_CASE_INFO = """
SELECT DISTINCT
    U1_CASE.ID,
    U1_CASE.FULL_NUMBER,
    U1_CASE.JUDICIAL_UID,
    GROUPCONTENT.USERNAME,
    U1_CASE.VERDICT_DATE,
    CATALOGCONTENT_VERDICT.NAME AS VERDICT_NAME
FROM
    U1_CASE
    LEFT JOIN GROUPCONTENT
        ON U1_CASE.JUDGE_ID = GROUPCONTENT.GROUPCONTENTID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_VERDICT
        ON U1_CASE.VERDICT_ID = CATALOGCONTENT_VERDICT.CONTENTID
    LEFT JOIN U1_DEFENDANT
        ON U1_CASE.ID = U1_DEFENDANT.CASE_ID
WHERE
    UPPER(U1_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
"""

U1_GET_DEFENDANTS_INFO = """
SELECT
    U1_DEFENDANT.NAME,
    CATALOGCONTENT.NAME,
    U1_DEFENDANT.BIRTH_DATE,
    U1_DEFENDANT.MAIN_LAW_ARTICLE,
    U1_DEFENDANT.NATIVE
FROM
    U1_CASE
    LEFT OUTER JOIN U1_DEFENDANT
        ON U1_CASE.ID = U1_DEFENDANT.CASE_ID
    LEFT OUTER JOIN CATALOGCONTENT
        ON U1_DEFENDANT.SEX_ID = CATALOGCONTENT.CONTENTID
WHERE
    UPPER(U1_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
"""

U1_GET_SUD_ZASEDANIE_INFO = """
SELECT
    CATALOGCONTENT_EVENT_NAME.NAME AS EVENT_NAME,
    CATALOGCONTENT_EVENT_RESULT.NAME AS EVENT_RESULT,
    CATALOGCONTENT_REASON.NAME AS REASON_FOR_RESULT,
    U1_EVENT.EVENT_DATE
FROM
    U1_CASE
    LEFT JOIN U1_EVENT
        ON U1_CASE.ID = U1_EVENT.CASE_ID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_EVENT_NAME
        ON U1_EVENT.EVENT_NAME_ID = CATALOGCONTENT_EVENT_NAME.CONTENTID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_EVENT_RESULT
        ON U1_EVENT.EVENT_RESULT_ID = CATALOGCONTENT_EVENT_RESULT.CONTENTID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_REASON
        ON U1_EVENT.REASON_FOR_RESULT_ID = CATALOGCONTENT_REASON.CONTENTID
WHERE
    UPPER(U1_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
    AND U1_EVENT.EVENT_NAME_ID IN (50760019, 50760007, 50760010)
ORDER BY
    U1_EVENT.EVENT_DATE
"""

U1_GET_PARTS_INFO = """
SELECT
    U1_PARTS.NAME
FROM
    U1_CASE
    LEFT OUTER JOIN U1_PARTS
        ON U1_CASE.ID = U1_PARTS.CASE_ID
WHERE
    UPPER(U1_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
    AND U1_PARTS.PART_TYPE_ID IN (910240008)
"""

U1_GET_PARTS_REQUISITE = """
SELECT
    CAT_PARTS.ID,
    CAT_PARTS.NAME,
    CAT_PARTS_REQUISITE.NAME AS REQUISITE_NAME,
    CAT_PARTS_REQUISITE.INN_STR,
    CAT_PARTS_REQUISITE.KPP_STR,
    CAT_PARTS_REQUISITE.ACCOUNT_STR,
    CAT_PARTS_REQUISITE.BANK_STR,
    CAT_PARTS_REQUISITE.BIK_STR,
    CAT_PARTS_REQUISITE.CORRESP_ACCOUNT_STR
FROM
    CAT_PARTS
    LEFT JOIN CAT_PARTS_REQUISITE
        ON CAT_PARTS_REQUISITE.PART_ID = CAT_PARTS.ID
WHERE
    CAT_PARTS.NAME = ?
"""

# ─── Уголовные материалы ─────────────────────────────────────────────

M_GET_CASE_INFO = """
SELECT DISTINCT
    M_CASE.ID,
    M_CASE.FULL_NUMBER,
    M_CASE.JUDICIAL_UID,
    GROUPCONTENT.USERNAME,
    M_CASE.VERDICT_DATE,
    CATALOGCONTENT_VERDICT.NAME AS VERDICT_NAME,
    CATALOGCONTENT_SUB_TYPE.NAME AS SUB_TYPE_NAME
FROM
    M_CASE
    LEFT JOIN GROUPCONTENT
        ON M_CASE.JUDGE_ID = GROUPCONTENT.GROUPCONTENTID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_VERDICT
        ON M_CASE.VERDICT_ID = CATALOGCONTENT_VERDICT.CONTENTID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_SUB_TYPE
        ON M_CASE.M_SUB_TYPE = CATALOGCONTENT_SUB_TYPE.CONTENTID
WHERE
    UPPER(M_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
"""

# В материалах: статья хранится на M_CASE (не на M_PARTS),
# а поле NATIVE (уроженец) в этой картотеке отсутствует
M_GET_DEFENDANTS_INFO = """
SELECT
    M_PARTS.NAME,
    CATALOGCONTENT.NAME,
    M_PARTS.BIRTH_DATE,
    M_CASE.MAIN_LAW_ARTICLE
FROM
    M_CASE
    LEFT OUTER JOIN M_PARTS
        ON M_CASE.ID = M_PARTS.CASE_ID
    LEFT OUTER JOIN CATALOGCONTENT
        ON M_PARTS.SEX_ID = CATALOGCONTENT.CONTENTID
WHERE
    UPPER(M_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
    AND M_PARTS.PART_TYPE_ID IN (910240102)
"""

M_GET_SUD_ZASEDANIE_INFO = """
SELECT
    CATALOGCONTENT_EVENT_NAME.NAME AS EVENT_NAME,
    CATALOGCONTENT_EVENT_RESULT.NAME AS EVENT_RESULT,
    CATALOGCONTENT_REASON.NAME AS REASON_FOR_RESULT,
    M_EVENT.EVENT_DATE
FROM
    M_CASE
    LEFT JOIN M_EVENT
        ON M_CASE.ID = M_EVENT.CASE_ID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_EVENT_NAME
        ON M_EVENT.EVENT_NAME_ID = CATALOGCONTENT_EVENT_NAME.CONTENTID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_EVENT_RESULT
        ON M_EVENT.EVENT_RESULT_ID = CATALOGCONTENT_EVENT_RESULT.CONTENTID
    LEFT JOIN CATALOGCONTENT CATALOGCONTENT_REASON
        ON M_EVENT.REASON_FOR_RESULT_ID = CATALOGCONTENT_REASON.CONTENTID
WHERE
    UPPER(M_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
    AND M_EVENT.EVENT_NAME_ID IN (70300000)
ORDER BY
    M_EVENT.EVENT_DATE
"""

M_GET_PARTS_INFO = """
SELECT
    M_PARTS.NAME
FROM
    M_CASE
    LEFT OUTER JOIN M_PARTS
        ON M_CASE.ID = M_PARTS.CASE_ID
WHERE
    UPPER(M_CASE.FULL_NUMBER COLLATE PXW_CYRL)
        LIKE UPPER('__CASE_NUMBER__' COLLATE PXW_CYRL)
    AND M_PARTS.PART_TYPE_ID IN (910240008)
"""