/* ============================================================
   Архив постановлений на оплату адвокатов
   Firebird 2.5, диалект 3

   Выполнять в IBExpert: Tools -> Script Executive.
   Предварительно создайте базу (или раскомментируйте CREATE DATABASE
   и выполните его отдельно, подставив свой путь):

   CREATE DATABASE 'C:\data\lawyer_fee\DECREE_ARCHIVE.FDB'
     USER 'SYSDBA' PASSWORD 'masterkey'
     PAGE_SIZE 8192
     DEFAULT CHARACTER SET WIN1251;
   ============================================================ */

/* ---------- Основная таблица постановлений ---------- */

CREATE TABLE DECREES (
    ID              INTEGER NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USERNAME        VARCHAR(100) NOT NULL,
    CASE_NUMBER     VARCHAR(100),
    CASE_SOURCE     VARCHAR(10),
    LAWYER_FIO      VARCHAR(200),
    DEFENDANT_FIO   VARCHAR(200),
    SERVICES_TOTAL  DECIMAL(15,2),
    EXTRA_TOTAL     DECIMAL(15,2),
    FULL_TOTAL      DECIMAL(15,2),
    SNAPSHOT        BLOB SUB_TYPE TEXT,
    CONSTRAINT PK_DECREES PRIMARY KEY (ID)
);

CREATE GENERATOR GEN_DECREES_ID;

SET TERM ^ ;
CREATE TRIGGER DECREES_BI FOR DECREES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_DECREES_ID, 1);
END^
SET TERM ; ^

CREATE INDEX IDX_DECREES_USERNAME ON DECREES (USERNAME);
CREATE DESCENDING INDEX IDX_DECREES_CREATED ON DECREES (CREATED_AT);

/* ---------- Услуги адвоката ---------- */

CREATE TABLE DECREE_SERVICES (
    ID           INTEGER NOT NULL,
    DECREE_ID    INTEGER NOT NULL,
    SERVICE_DATE DATE,
    SERVICE_NAME VARCHAR(300),
    AMOUNT       DECIMAL(15,2),
    IS_SESSION   SMALLINT DEFAULT 0,
    CONSTRAINT PK_DECREE_SERVICES PRIMARY KEY (ID),
    CONSTRAINT FK_DSVC_DECREE FOREIGN KEY (DECREE_ID)
        REFERENCES DECREES (ID) ON DELETE CASCADE
);

CREATE GENERATOR GEN_DECREE_SERVICES_ID;

SET TERM ^ ;
CREATE TRIGGER DECREE_SERVICES_BI FOR DECREE_SERVICES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_DECREE_SERVICES_ID, 1);
END^
SET TERM ; ^

CREATE INDEX IDX_DSVC_DECREE ON DECREE_SERVICES (DECREE_ID);

/* ---------- Дополнительные постановления ---------- */

CREATE TABLE DECREE_EXTRAS (
    ID          INTEGER NOT NULL,
    DECREE_ID   INTEGER NOT NULL,
    SOURCE_NAME VARCHAR(300),
    DECREE_DATE DATE,
    AMOUNT      DECIMAL(15,2),
    CONSTRAINT PK_DECREE_EXTRAS PRIMARY KEY (ID),
    CONSTRAINT FK_DEXT_DECREE FOREIGN KEY (DECREE_ID)
        REFERENCES DECREES (ID) ON DELETE CASCADE
);

CREATE GENERATOR GEN_DECREE_EXTRAS_ID;

SET TERM ^ ;
CREATE TRIGGER DECREE_EXTRAS_BI FOR DECREE_EXTRAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_DECREE_EXTRAS_ID, 1);
END^
SET TERM ; ^

CREATE INDEX IDX_DEXT_DECREE ON DECREE_EXTRAS (DECREE_ID);

COMMIT;
